{"name": "test_login_with_invalid_email_and_valid_password", "status": "passed", "start": 1711091680854, "stop": 1711091682115, "uuid": "5567a7ed-cd55-4830-a631-940b473f1a61", "historyId": "cd3500ccb6b16a398d3c5c6e5203a23d", "testCaseId": "cd3500ccb6b16a398d3c5c6e5203a23d", "fullName": "tests.test_login.TestLogin#test_login_with_invalid_email_and_valid_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "CTIVL0145"}, {"name": "thread", "value": "12020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}