{"name": "test_login_with_invalid_email_and_valid_password", "status": "passed", "start": 1710960966132, "stop": 1710960967735, "uuid": "ad4ece43-35b3-4382-99c8-e855003c12c2", "historyId": "cd3500ccb6b16a398d3c5c6e5203a23d", "testCaseId": "cd3500ccb6b16a398d3c5c6e5203a23d", "fullName": "tests.test_login.TestLogin#test_login_with_invalid_email_and_valid_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "CTIVL0145"}, {"name": "thread", "value": "12044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}