{"name": "test_login_with_valid_email_and_invalid_password", "status": "passed", "start": 1711026041273, "stop": 1711026044315, "uuid": "5b2c4161-69a8-4514-aa1d-62b54f4d9446", "historyId": "a87129e8bc488f2c2b04474f72c047f1", "testCaseId": "a87129e8bc488f2c2b04474f72c047f1", "fullName": "tests.test_login.TestLogin#test_login_with_valid_email_and_invalid_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "CTIVL0145"}, {"name": "thread", "value": "20048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}