{"name": "test_login_with_invalid_email_and_valid_password", "status": "passed", "start": 1710959995581, "stop": 1710959996926, "uuid": "92917116-3a66-4be7-b1b7-bb78296515b4", "historyId": "cd3500ccb6b16a398d3c5c6e5203a23d", "testCaseId": "cd3500ccb6b16a398d3c5c6e5203a23d", "fullName": "tests.test_login.TestLogin#test_login_with_invalid_email_and_valid_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "CTIVL0145"}, {"name": "thread", "value": "11000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}